=== oss-slu/mithradatium/reports/report_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"required": [
		"mithridatium_version",
		"timestamp_utc",
		"model_path",
		"defense",
		"dataset",
		"results"
	],
	"properties": {
		"mithridatium_version": { "type": "string" },
		"timestamp_utc": { "type": "string" },
		"model_path": { "type": "string" },
		"defense": { "type": "string" },
		"dataset": { "type": "string" },
		"results": { "type": "object" }
	},
	"additionalProperties": true
}

=== oss-slu/mithradatium/test_report.json
{
  "mithridatium_version": "0.1.0",
  "timestamp_utc": "2025-11-29T06:57:59.656900Z",
  "model_path": "models/resnet18_poison.pth",
  "defense": "strip",
  "dataset": "cifar10",
  "results": {
    "entropies": [
      0.8908131718635559,
      1.0416946411132812,
      1.25931978225708,
      1.1651346683502197,
      1.1246498823165894,
      0.821864902973175,
      1.1872310638427734,
      0.654247522354126,
      1.3309650421142578,
      0.8633555173873901,
      0.8300310969352722,
      1.0243608951568604,
      0.8220431208610535,
      0.8678932785987854,
      0.7854791879653931,
      0.9563668966293335,
      1.1305217742919922,
      1.2904465198516846,
      1.1605632305145264,
      0.8708277940750122,
      1.303524136543274,
      1.0695277452468872,
      0.8418548107147217,
      0.7635111212730408,
      1.0756092071533203,
      0.7455508708953857,
      1.1538797616958618,
      1.1432048082351685,
      0.8330492973327637,
      1.124779224395752,
      0.9224187731742859,
      1.1702289581298828
    ],
    "num_bases": 32,
    "num_perturbations": 16
  }
}
